### ISSUE TITLE
Slug size huge after last update

### ISSUE THREAD

**Issue by henrik** [heroku/heroku-buildpack-ruby#1046]
Haven't looked into this deeply but thought I'd flag it ASAP in case others run into it.

Yesterday we got a slug size of ~230 MB but today it was ~900 MB, well over Heroku's 500 MB limit.

So far in our research, it seems the culprit may be https://github.com/heroku/heroku-buildpack-ruby/commit/0449897f249bacc66f57c62e891dd847a40daaba.

We locked the buildpack to the preceding commit, https://github.com/heroku/heroku-buildpack-ruby/commit/35463d0715ffd59bce292675f8a965725e6ba9f0 (by specifying it as `https://github.com/heroku/heroku-buildpack-ruby.git#35463d0715ffd59bce292675f8a965725e6ba9f0`), and then we managed to deploy again.

This is all with the same code on our side: a commit succeeded yesterday, then we made an `--allow-empty` commit on top of that which failed to deploy, and another `--allow-empty` which succeeded after locking the buildpack. (We did it that way to try to confirm the issue.)

This is a Rails 5.0 app on Ruby 2.6.6p146 bundled with Bundler 2.1.2.

**Comment by edmorley** [comment]
@henrik Hi :-) Thank you for filing this issue and the excellent detail in it!

The Ruby buildpack maintainer will be online later and will dig in more, but for now for anyone else affected by this a workaround is to switch to the stable published version of the Ruby buildpack (the `heroku/ruby` shorthand alias) rather than using the edge/development version from `https://github.com/heroku/heroku-buildpack-ruby`. (See https://devcenter.heroku.com/articles/buildpacks and https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-buildpacks)

Another advantage of using the published buildpack release from the buildpack registry, is that the official language buildpacks are pre-cached on the build workers, so saves the git clone of the repository at the start of every build.

@schneems There are the following tickets related to this:
https://heroku.support/910531
https://heroku.support/910504
https://heroku.support/910502
https://heroku.support/910438
https://heroku.support/910389

**Comment by henrik** [comment]
Also seeing it with Rails 4.2 on Ruby 2.6.6p146 bundled with Bundler 1.17.3 – it's the same Rails app. We had the poor timing of attempting a Rails upgrade that ran into this issue :)

Thank you, @edmorley! Good call with the stable one. Not sure why we've been using edge – will look into.

The first of those support issues (910531) is from our team :)

**Comment by henrik** [comment]
Just to report back, we switched to the stable "heroku/ruby" buildpack and were able to deploy the app – first on Rails 4, then with the Rails 5 upgrade.

**Comment by edmorley** [comment]
Great! Glad that worked :-)

**Comment by schneems** [comment]
I reverted the commit. It looks like even though the bundle config is exactly the same values, that there is different behavior between these two commands:

```
bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
BUNDLE_WITHOUT=development:test BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
```

What's happening is that using `bundle install` with flags installs your gems to this directory:

```
~ $ bundle show rake
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1
~ $ bundle exec gem env | grep "GEM PATHS" -A1
  - GEM PATHS:
     - /app/vendor/bundle/ruby/2.6.0
```

But using `bundle install` with environment variables installs them to this directory:

```
~ $ bundle show rake
/app/vendor/bundle/gems/rake-13.0.1
~ $ bundle exec gem env | grep "GEM PATHS" -A1
  - GEM PATHS:
     - /app/vendor/bundle
```

The reason that slug size is ballooning is that bundler cannot find the gems it installed previously, so it's re-installing ALL of your gems to a new, different directory. This means your app will now have 2 copies of each gem which is why the slug size shoots through the roof. 

I don't know why this behavior is different, but I've got a way of reproducing the behavior you've reported. I'm going to work on debugging this issue so that I can understand the root cause.

**Comment by schneems** [comment]
Update: I've reported this behavior back to the bundler team in https://github.com/rubygems/rubygems/issues/3890 i've attached a reproduction example with docker that does not depend on Heroku.

**Comment by f1sherman** [comment]
We saw the same behavior (~3x slug size) using bundler 2.0.2. We've since rolled back to the published ruby buildpack and that fixed the issue.

**Comment by schneems** [comment]
Possibly related: https://heroku.support/910536

**Comment by schneems** [comment]
@f1sherman I wasn't able to reproduce the increased slug size with Bundler 2.1.4, but I just tried and can reproduce with bundler 2.0.2. I think the easiest thing for me to do will be to upgrade 2.x bundler users to 2.1.4 there, but that still leaves the 1.17.3 problem.
