### ISSUE TITLE
Remove vendor/cache after bundle install if BUNDLE_LOCAL set, i.e., `--local` used.

### ISSUE THREAD

**Issue by matthewbennink** [heroku/heroku-buildpack-ruby#1156]
I haven't found any GH issues that best describe this scenario, so opening this one for conversation. We use `bundle package` to keep a copy of gem files inside the (default?) vendor/cache directory. This directory is checked into version control and is used (via `heroku config:set BUNDLE_LOCAL=1`, #1107) to install gems locally. So far, so good.

The question I have is whether it's appropriate for the ruby buildpack to remove the `vendor/cache` directory if it exists to reduce the slug size. It saved us roughly 40mb, but of course depends on how many gems a project has. It could be guarded by the presence of the `BUNDLE_LOCAL` to only remove it if installing gems locally, or perhaps some new ENV variable, allowing users to opt-in to the change. Otherwise, I fear it may not be backwards-compatible since there's no reason a project couldn't use `vendor/cache` for other data.

At the moment, we have a workaround, which is to use a second buildpack that removes the directory. It works, but I do feel that many others could benefit from having this functionality inside the official ruby buildpack, especially since it doesn't seem too esoteric.

Thanks for your time!

**Comment by schneems** [comment]
Hello! Thanks for opening an issue! Can you link to your buildpack so others who want to use it in the short term can?

I understand your use case as described. In the past we've been against vendoring via `bundle package` due to possible system differences (i.e. packaging a mswin specific gem and then deploying to Heroku which runs on Linux). I believe that some of the changes in Bundler 2.2 allow us to change behavior in the buildpack i.e. https://github.com/heroku/heroku-buildpack-ruby/blob/fe4db44101a9482c09cadd6e5b5ebf112e278f79/lib/language_pack/ruby.rb#L819-L829

I think your idea is a good one, but also I want to be up front that I'm working on a re-write of the buildpack github.com/heroku/heroku-buildpack-ruby-experimental as well as some feature development internally. I've not been able to get to all of the buildpack features I would like as quickly as I would like.

I think in the short term I would encourage people to use a buildpack in the short term.

**Comment by schneems** [comment]
Thanks for the report. I won't be implementing this soon. I think the general workaround of using another buildpack or the `.slugignore` file would be a recommended path forward.
