### ISSUE TITLE
Heroku-18 stack fails when trying to build project using split Gemfile.lock (built by bundler 2.2.21)

### ISSUE THREAD

**Issue by aowens-ampion** [heroku/heroku-buildpack-ruby#1172]
After watching https://github.com/heroku/heroku-buildpack-ruby/issues/1167 get remediated by adding bundler 2.2.21 to the tech stack, we began experiencing build failures.

When the new (2.2.21) bundler would generate the `Gemfile.lock` file, our gem sources would be split into two blocks, making it easier for bundler to know where to source the gems (which was the point of the bundler upgrade, I believe).  This new format would fail when trying to build, giving a ```heroku Could not detect rake tasks ! ensure you can run `$ bundle exec rake -P` against your app ! and using the production group of your Gemfile.```  

The help text suggested checking my Gemfile.lock into git, and trying again.  (The Gemfile.lock was committed to git).

**Issue**
Build fails on Heroku-18, when using multiple gem sources in the Gemfile.lock file.  Examples:

```
GEM
  remote: https://rails-assets.org/
  specs: yadda, yadda
```

and beneath that block...

```
GEM
  remote: https://rubygems.org/
  specs: yadda, yadda
```

**Expected results**

Project builds successfully on heroku-18 and using a Gemfile.lock generated by bundler 2.2.21

**Actual results**

Project fails to build giving the following error:

```
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
 !     your Gemfile. Run `bundle install` elsewhere and add the
 !     updated Gemfile.lock to version control.
 !     
 !     If this is a development machine, remove the /tmp/build_773438b3/Gemfile freeze
 !     by running `bundle install --no-deployment`.
 !     
 !     The list of sources changed
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:13:in `setup'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler.rb:149:in `setup'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
 !     from /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
 !     from /tmp/build_773438b3/config/boot.rb:3:in `<top (required)>'
 !     from /tmp/build_773438b3/bin/rake:7:in `require_relative'
 !     from /tmp/build_773438b3/bin/rake:7:in `<main>'
 !
```

**Comment by schneems** [comment]
You can use an older bundler version using these docs for the short term https://devcenter.heroku.com/articles/bundler-version#using-an-older-version-of-bundler but know that there's a security vulnerability in anything less than bundler 2.2.18.

To be able to reproduce and debug this can you please open a support ticket help.heroku.com search for "bundler fails" and open a ticket with access to your app?

**Comment by beccachapin** [comment]
Did you get any resolution to this? I have hit the same issue with sidekiq-pro being split into separate sources and I have tried everything. In order to get our project to build, I had to roll back to bundler 1.17.3 (next supported bundler per https://devcenter.heroku.com/articles/ruby-support#libraries) but as @schneems mentioned this has a security vulnerability. I have a support ticket opened with Heroku, but they

**Comment by h-lame** [comment]
I've just encountered this and what's most worrying to me is that it looks like while it does install bundler 2.2.21, the error messages we got from the build suggest it's still _using_ bundler 2.1.4 that ships with ruby.

For example in @aowens-ampion's build output we have the line:

```
 !     /tmp/build_773438b3/vendor/ruby-2.7.0/lib/ruby/2.7.0/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
```

Which is suspicious for 2 reasons:

1. that path is for the bundler shipped with ruby 2.7, the build pack installs bundler 2.2.21 somewhere else that should have a path with a component like `bundler-2.2.1` in it
2. the line number of definition.rb in that message should be [441 for bundler 2.2.21](https://github.com/rubygems/rubygems/blob/bundler-v2.2.21/bundler/lib/bundler/definition.rb#L441) and would be [466 only if it was using 2.1.4](https://github.com/rubygems/bundler/blob/v2.1.4/lib/bundler/definition.rb#L466).

The problem here might be that we remove the BUNDLED_WITH after we've detected the bundler major version, but don't replace it with the actual blessed version we're going to use.  This means bundler won't auto switch to the right version and so we fallback to the shipped by ruby version.

**Comment by h-lame** [comment]
After exploring the buildpack a bit more, I spotted that there's a lot of heavy lifting in `LanguagePack::Ruby#build_bundler` and similarly in `LanguagePack::Helpers::BundlerWrapper#ruby_version` to setup paths and such, I assume to _force_ the command to use the freshly installed bundler version.  I don't see the same happening for other places in the buildpack that run commands, (e.g. like `LanguagePack::Helpers::RakeRunner#load_rake_tasks!` which is what fails during the build).  It doesn't feel right that we should have to do all that heavy lifting though, but maybe we do?

**Comment by schneems** [comment]
Last message was quite awhile ago. If you're seeing something like this, please open a support ticket on Heroku
