### ISSUE TITLE
Add support for libvips

### ISSUE THREAD

**Issue by dwightwatson** [heroku/heroku-buildpack-ruby#1200]
[Rails 7.0.0 Alpha 1](https://weblog.rubyonrails.org/2021/9/15/Rails-7-0-alpha-1-released/) has just been released, which makes a change to the [default variant processor](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#activestorage-variant-processor-changed-to-vips). `libvips` is now the default instead of `ImageMagick`. 

While `ImageMagick` is still supported it seems reasonable that Heroku should support the default out of the box so that additional configuration isn't required to get a fresh Rails 7 app up and running. Furthermore `libvips` is a more performant option.

## Added info by maintainer, please don't change:

- GUS-W-9927197

**Comment by schneems** [comment]
Thanks for the issue! I was just reviewing the rails changelog and working on getting Rails 7 alpha docs up when I noticed this.

## Extra context

We've also have some related internal tickets (reference only, non-herokai won't be able to see them):

- https://heroku.support/876824
- https://heroku.support/851607

## Short term workaround

Here's a thread of people trying to get libvips working on heroku https://github.com/janko/image_processing/issues/32#issuecomment-724276854. 

As a short term solution: I was able to get it working via the `heroku/community/apt` buildpack and adding this to the `Aptfile`.

```
libglib2.0-0
libglib2.0-dev
libpoppler-glib8
libheif
libvips-dev
libvips
```

We do have an "active storage previews" buildapck but I'm pretty sure it doesn't install libvips https://devcenter.heroku.com/articles/active-storage-on-heroku

## Long term solution

I'm going to bring up adding libvips to our default image. If you're curious, our stack image definitions are also open source https://github.com/heroku/stack-images.

**Comment by dwightwatson** [comment]
Great to hear - I'll have a play with the `Aptfile` solution too.

Would be awesome to see it in the default image (with the HEIF support too).

Thanks!

**Comment by dwightwatson** [comment]
I opened a ticket (1030923) but I don't think it ended up assigned to you.

We were able to debug that heroku-20/Ubuntu 20.04 installs libvips 8.9.1, when the current version is 8.11.3.

Unfortunately [there appears to be an issue prior to version 8.11.1](https://github.com/libvips/ruby-vips/issues/311) which prevents libvips from working with HEIF. HEIF support is pretty important as iPhones have used it as the default photo format for a while.

Ideally these newer versions could be baked into the buildpack?

**Comment by dwightwatson** [comment]
I know it's hot off the press (Rails 7.0.0 has just been tagged), but I wonder if there's been any progress getting `libvips` into the buildpack?

**Comment by dwightwatson** [comment]
Hey @schneems don't mean to be a bother but wondering if there's any progress internally about this? Would be super helpful to those of us leveraging ActiveStorage to know whether this will actually happen.

**Comment by jcupitt** [comment]
Hello, I'm one of the libvips maintainers.

Another large plus for building your own libvips binary is security. The libvips that comes with Debian (for example) enables all possible loaders, and some of those load libraries have not been fuzzed. I expect they could be exploited easily, and this would obviously be bad for your customers.

libvips has been fuzzed for a couple of years now in oss-fuzz:

https://github.com/google/oss-fuzz/tree/master/projects/libvips

I suggest you only enable that set of loaders. They should be pretty safe for untrusted input.

In fact I'd go even further and also omit JXL for now. Fuzzing is still finding issues in libjxl relatively frequently.

**Comment by dwightwatson** [comment]
@jcupitt that's great to know. I don't suppose you'd have any guidance on building libvips on Heroku?

**Comment by jcupitt** [comment]
@dwightwatson sorry, I use ruby and heroku a bit, but I'm not an expert on slugs and all that stuff.

I was partly involved in https://elements.heroku.com/buildpacks/brandoncc/heroku-buildpack-vips , I don't know if that's helpful.

**Comment by wdiechmann** [comment]
hi @jcupitt 

TL;DR: will heroku-buildpack-vips support Ruby 3.0.3 any time soon?

LR: I ended up here after a somewhat rather lengthy detour 😓  for just wanting the latest/greatest in Apple Silicon, arm64 and what-not - and obviously libvips - and even though I've battled my way through/around quite a few issues along the road I fear this will be the end of it 😭 

The "original" ruby buildpack was not enough so I did `dokku buildpacks:add --index 2 greybox https://github.com/brandoncc/heroku-buildpack-vips`

which now hands me this:

```
src % git push staging staging:master
Enumerating objects: 3981, done.
Counting objects: 100% (3981/3981), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3909/3909), done.
Writing objects: 100% (3981/3981), 3.56 MiB | 5.92 MiB/s, done.
Total 3981 (delta 2763), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2763/2763), done.
-----> Cleaning up...
-----> Building greybox from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi ruby nodejs
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/brandoncc/heroku-buildpack-vips
=====> Detected Framework: vips (heroku-20 stack)
-----> Vendoring binaries
       Fetching /tmp/buildpackDneo5/build/heroku-20.tar.gz
-----> Configuring build environment
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing greybox...
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
       No release task found, skipping
-----> App Procfile file found
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying greybox via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
       Waiting for 10 seconds (web.1)
3a8beed3537b5710a50e0b8077133138cbefdb73b3d8372ea411a5f15e8e5b4b
remote:  !     App container failed to start (web.1)
=====> Start of greybox container output (web.1)
       /usr/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.7.0, but your Gemfile specified 3.0.3 (Bundler::RubyVersionMismatch)
        from /usr/lib/ruby/2.7.0/bundler/definition.rb:470:in `validate_runtime!'
        from /usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'
        from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
        from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
        from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /app/config/boot.rb:3:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
---8<---
       /usr/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.7.0, but your Gemfile specified 3.0.3 (Bundler::RubyVersionMismatch)
        from /usr/lib/ruby/2.7.0/bundler/definition.rb:470:in `validate_runtime!'
        from /usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'
        from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
        from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
        from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /app/config/boot.rb:3:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
=====> End of greybox container output (web.1)
remote: 2022/05/24 17:06:44 exit status 1
remote: parallel: This job failed:
remote: /var/lib/dokku/plugins/available/scheduler-docker-local/bin/scheduler-deploy-process-container greybox herokuish dokku/greybox:latest latest web 1 1
remote: 2022/05/24 17:06:45 exit status 1
remote: 2022/05/24 17:06:45 exit status 1
To greybox:greybox
 ! [remote rejected] staging -> master (pre-receive hook declined)
error: failed to push some refs to 'greybox:greybox'
?1 src % 
```

**Comment by dwightwatson** [comment]
Unfortunately it seems that [`libvips` did not make it into `heroku-22`](https://devcenter.heroku.com/articles/stack-packages).

**Comment by dzuelke** [comment]
Thank you for your patience, everybody.

`libvips` is now available on all Heroku stacks, so the `ruby-vips` Gem will build without third-party buildpacks: https://devcenter.heroku.com/changelog-items/2549

Please bear in mind that rollouts of stack image updates to Private Spaces take additional time and will happen over the next few days, so if your app runs in a Private Space, check with a `heroku run 'ls /usr/lib/x86_64-linux-gnu/libvips.so.*'` whether the libraries are there yet before building against them.

**Comment by jcupitt** [comment]
Hi @dzuelke, this is great!

I noticed a possible problem though, looking at the changelog you have:

```
Added libcfitsio5 version 3.430-2
Added libhdf5-100 version 1.10.0-patch1+docs-4
Added libmatio4 version 1.5.11-1
Added libopenjp2-7 version 2.3.0-2build0.18.04.1
Added libopenslide0 version 3.4.1+dfsg-2
```

If these libraries were added for libvips' benefit, I'm not sure this is a good idea. They have not been fuzzed (as far as I know) and are probably trivially hackable. I know at least `libmatio` makes zero attempt to sanitise user input and the maintainer has no intention of ever hardening the reader against untrusted input files.

With this set of libraries, any rails application which lets activestorage see untrusted data will almost certainly be vulnerable to remote code execution attacks with crafted files.

I would very strongly urge you to only build libvips with image format libraries that we've fuzzed. You can see our fuzzing set up here:

https://github.com/libvips/libvips/blob/master/fuzz/oss_fuzz_build.sh

I would also pick pdfium over poppler (poppler is GPL), but of course that's your call.

**Comment by jcupitt** [comment]
Hey @dzuelke, thank for the quick reply.

Yes, I wondered if you were just using the ubuntu builds, that's a shame.

libvips 8.13 and later has a thing to block untrusted loaders: 

https://www.libvips.org/2022/05/28/What's-new-in-8.13.html#blocking-of-unfuzzed-loaders

It's off by default. 

I've suggested to `image_processing` (the package that rails uses to call libvips) that they might set the env var `VIPS_BLOCK_UNTRUSTED`:

https://github.com/janko/image_processing/issues/105#issuecomment-1450274467

Or perhaps heroku could set this by default somewhere? You'll know far more about this than me!

This won't help older libvips installs, of course.

**Comment by jcupitt** [comment]
Unfortunately, ubuntu-22 shipped with libvips 8.12, so I think none of these builds will have the thing to block untrusted loaders :(

Perhaps libvips should be removed from heroku until the next LTS, which should have the thing to block untrusted loaders?

The alternative would be to build your own libvips binary with only the trusted loaders included (this is what the various buildpacks do), but that would be significantly more work for you, of course.

Perhaps heroku could bless and help maintain an official libvips buildpack? That might be an easy compromise.

**Comment by dzuelke** [comment]
Yeah, 8.12 unfortunately :(

FWIW, [having just the presence of `VIPS_BLOCK_UNTRUSTED` trigger the blocking](https://github.com/libvips/libvips/blob/65c99219af5b3f4a8e9d4a9daf7886a6c97cf619/libvips/iofuncs/init.c#L675) isn't ideal, as that makes it difficult to "unset" the env var if a user wants to override it (e.g. by setting it to an empty value to override the default blocking), but I guess that ship has sailed now that it's in released code 😬.

We'll discuss a "libvips-fuzzed" buildpack internally.

The most important thing for us is to link against as many libraries from the stack as possible, because our stack images underpin running dynos, meaning an update to packages affects all apps immediately thanks to dynamic linking.

Having libraries supplied by a buildpack, on the other hand, means customers only get their packages updated when they redeploy their apps.

Maybe you folks at libvips.org should provide a PPA with more recent builds for Ubuntu LTS versions? ;)

**Comment by jcupitt** [comment]
> having just the presence of VIPS_BLOCK_UNTRUSTED trigger the blocking isn't ideal, as that makes it difficult to "unset" the env var if a user wants to override it

Oh hmm I thought it was easy to unset env vars. Are there times when this is difficult?

> Maybe you folks at libvips.org should provide a PPA with more recent builds for Ubuntu LTS versions? ;)

Ooooof, we're really hoping to not do any more packaging :( It's so much work.

I suppose I'm concerned that by shipping a libvips binary that's not suited for untrusted data, heroku might end up accidentally discouraging community packaging of more secure versions. That would be a very unfortunate outcome for everyone.

**Comment by dzuelke** [comment]
> > having just the presence of VIPS_BLOCK_UNTRUSTED trigger the blocking isn't ideal, as that makes it difficult to "unset" the env var if a user wants to override it
> 
> Oh hmm I thought it was easy to unset env vars. Are there times when this is difficult?

Yup :) Imagine a `Dockerfile` that sets `VIPS_BLOCK_UNTRUSTED=1`, now you can not `docker run … --env VIPS_BLOCK_UNTRUSTED= …` to "remove" that variable - it'll be an empty string, which in the `if` will evaluate to `true`.

Same on Heroku and any other platforms... you can set variables to override defaults a buildpack or the platform might set, but the "best" you can do is to make it an empty string.

Since you now have released code with this behavior, it would be a bit risky to change it, since there *might* be people who just set the variable to an empty value (as opposed to "1"), and suddenly, they'd "lose" the blocking with an update.

Although if you clearly document it, or emit a warning now that it will change in the future if the value is empty... alternatively, have explicit "0", "no", "false" values to disable the blocking maybe?

> > Maybe you folks at libvips.org should provide a PPA with more recent builds for Ubuntu LTS versions? ;)
> 
> Ooooof, we're really hoping to not do any more packaging :( It's so much work.

Yup, we know, that's why we try to avoid it, too ;)

> I suppose I'm concerned that by shipping a libvips binary that's not suited for untrusted data, heroku might end up accidentally discouraging community packaging of more secure versions. That would be a very unfortunate outcome for everyone.

Yeah I know what you mean.

I'm also looking through Rails' ActiveStorage and the `image_processing` Gem to understand how they treat MIME types and whether they rely fully on auto-detecting file types via Vips' loaders.

Because if uploading an `image/png` forcefully uses Vips' PNG loader, or if Rails uses file contents for MIME detection and not extension or `Content-Type`, this will be a non issue - uploading a `.mat` file with a bogus Content-Type and extension `image/png` would then not invoke the `matio` loader, and Rails doesn't allow "critical" file formats from your list of unfuzzed libraries for image processing: https://guides.rubyonrails.org/configuring.html#config-active-storage-variable-content-types

**Comment by ngobin** [comment]
Hi, it seems the Heroku-24 stack (available since October 30, 2024) [now includes libvips](https://devcenter.heroku.com/articles/stack-packages) 8.15.1-1.1build4.

Is this issue now effectively addressed by upgrading to stack 24? Is it just a matter of adding VIPS_BLOCK_UNTRUSTED=1 to our environment variables to block the untrusted loaders?

**Comment by RyanTG** [comment]
I'm also curious what the recommendations are for Heroku-24 stack. Thank you.

**Comment by ngobin** [comment]
Heroku-24 and new Heroku-26 stack use libvips 8.15.1 and 8.18.0 respectively, so both support the option to block untrusted loaders. Assuming one is using the image_processing gem, it [blocks untrusted loaders by default](https://github.com/janko/image_processing/issues/105) since version 2.0.0, released ~3 weeks ago. So if you're using Heroku-24 and image_processing 2.0.0 or newer, you don't need to worry about the environment variables any more; libvips will be secure by default. Setting the environment variable works if you're using an earlier version of image_processing.

If you need to allow untrusted loaders, you can add `Vips.block_untrusted(false)` in `config/initializers/image_processing.rb`.
