### ISSUE TITLE
Upgrade Bundler to >= 2.3.3

### ISSUE THREAD

**Issue by swrobel** [heroku/heroku-buildpack-ruby#1273]
Bundler is currently at 2.2.33 which prints out the following every time it runs:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

This seems to be fixed in 2.3.4 per https://github.com/rubygems/rubygems/issues/5234

**Comment by schneems** [comment]
BTW I deployed this today https://twitter.com/schneems/status/1499085205163945989

**Comment by schneems** [comment]
I had to rollback my deploy as it was causing problems 

- https://github.com/rubygems/rubygems/issues/5351 
- https://github.com/heroku/heroku-buildpack-ruby/issues/1280

**Comment by swrobel** [comment]
@schneems Bundler 2.3.9 is out with the fix https://github.com/rubygems/rubygems/issues/5351

**Comment by xmunoz** [comment]
Ping! We would also like support for a newer bundle version. Is there an estimate for when this will get released?

**Comment by bmulholland** [comment]
Yeah also I just hit https://github.com/rubygems/rubygems/issues/5351

It's been over a month since the fix was released, and no one from Heroku has even commented here. What's going on?

**Comment by bmulholland** [comment]
And actually, now I'm seeing that every single deploy I make to Heroku, even to known-good, previously-deployed commits, will not deploy to Heroku. They all fail with the same error: "uninitialized constant Gem::Source"

**Comment by sebnjk** [comment]
We also ran into this. @bmulholland it looks like clearing the cache only fixes it once. Subsequent builds may fail as it will keep trying to load bundler 2.3.7 for some reason (look at your build log, it probably contains something like `Using bundler 2.3.7` somewhere after a fresh build). This is probably due to the fact that [the default bundler version for Ruby 3.1.1 is 2.3.7](https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/). 

You can add the missing require statement to the `bin/bundle` binstub as indicated [here](https://github.com/rubygems/rubygems/issues/5351#issuecomment-1036373092):
```ruby
require "rubygems/source"
```

However, I don't think this is a particulary nice solution and don't know whether this breaks anything else. It'd probably easier for Heroku to push a buildpack version for Ruby 3.1.1 which contains a fixed bundler version or fixes the reference so it actually uses 2.2.33 on later builds.

@schneems any chance you could make this happen? :D Unless I missed something here, it kind of looks like right now all subsequent builds for people using the latest stable Ruby release (3.1.1) on Heroku are broken because it ships with a broken bundler...

**Comment by dentarg** [comment]
> it kind of looks like right now all subsequent builds for people using the latest stable Ruby release (3.1.1) on Heroku are broken

Indeed! I opened a new issue on the buildpack about this: https://github.com/heroku/heroku-buildpack-ruby/issues/1294

**Comment by sebnjk** [comment]
@schneems Thanks for updating bundler! I guess this issue can be closed now, too.
