### ISSUE TITLE
Default 3.0.3 download fails

### ISSUE THREAD

**Issue by uncleramsay** [heroku/heroku-buildpack-ruby#1279]
Hi, our app does not specify a specific version of Ruby, so we're getting the default version. Since the latest release this is failing:

```
-----> Using set buildpack heroku/ruby
  Failed to download a Ruby executable for bootstrapping!

  This is most likely a temporary internal error. If the problem
  persists, make sure that you are not running a custom or forked
  version of the Heroku Ruby buildpack which may need updating.

  url: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-3.0.3.tgz
```

The url listed in the output above gives me an 'Access Denied' message. Previous versions are working fine though.

**Comment by schneems** [comment]
The reason you're getting this failure is that the Ruby buildpack is written in Ruby. It needs a version of Ruby to run itself so the first thing it does is download a version of Ruby. We've pinned this behavior to move lock-step with our default version though that's an implementation detail.

What's happening is that we do not have a binary for Ruby 3.0.3 built for cedar-14 because cedar-14 was not a supported stack when Ruby 3.0.3 was released. 

To deploy I recommend you upgrade to a non EOL stack. It's also important to note that our stack images are based on ubuntu, so cedar-14 is based on Ubuntu 14 which is EOL and subject to unpatched security vulnerabilities. It is highly recommended to not run on a deprecated or EOL stack.

It's still possible to deploy to the cedar-14 stack (I'm assuming you're using CNB or pack as heroku disabled cedar-14 builds a long time ago). To do this you will need to pin to an older buildpack release, though if you run into issues you're off the supported path. I will not backport fixes to support an EOL stack.
