### ISSUE TITLE
assets:precompile fails, app build continues

### ISSUE THREAD

**Issue by calebthompson** [heroku/heroku-buildpack-ruby#358]
A gem was unable to be required during assets:precompile and caused a state where there were no assets available, but the app build continued: https://gist.github.com/calebthompson/7daa3551b44f8a2fe510

**Comment by calebthompson** [comment]
I was able to solve this for my own app by force pushing a different commit then pushing back in the one I wanted, but still an issue.

**Comment by schneems** [comment]
## General issue

We should clean up this error message:

```
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        This may be intentional, if you expected rake tasks to be run
remote:        cancel the build (CTRL+C) and fix the error then commit the fix:
remote:        
```

What happens is we use `rake -P` to detect available tasks. When this fails we can't reliably know if that's because you made a syntax error in your Rakefile and you really really relied on us to run `rake assets:precompile` or if it's because you didn't even ever consider we would try to run rake tasks for you (i.e. people deploying sinatra etc. don't expect us to run rake tasks) and you would be pissed if we suddenly stopped the deploy there. 

Unfortunately the expectation that we shouldn't be able to run `rake` on your app if you don't want us to is a long one. Some people explicitly rely on this behavior. 

I remember looking into this a really long time ago and a non-trivial number of apps were relying on this behavior. Not sure if they were Rails apps, perhaps we could scope the failure behavior to Rails 4+ apps with the expectation that "we should be able to run `rake -P` against your app" to run on Heroku.

## Your issue

> A gem was unable to be required

Any idea what caused this? If you can repro this scenario (i.e. a gem being installed but not require-able) I would want to look at it.

**Comment by calebthompson** [comment]
Yeah this gem was in the development group, the RAILS_ENV was set to development, but bundle didn't install that gem because it uses --without=development,test. Obviously the RAILS_ENV was wrong and we changed that which was part of the fix.

**Comment by matthewbjones** [comment]
We've also ran into this the other day as well. We had gem 'sqlite' in our development group, and we had a rake file under lib/tasks that has "require 'sqlite'".

When we went to push to Heroku, it wasn't able to run rake assets:precompile because sqlite gem was missing, but the build proceeded and successfully pushed the slug to our application, which then broke as 100% of our assets were missing.

We issued a rollback and removed the "require 'sqlite'" from our .rake file and re-pushed.

**Comment by drubin** [comment]
I am also having this issue. 

If the `Rakefile` is present it should be able to run in production mode at least for rails apps.
This is a requirement of rails being able to `rake db:migrate` and `rake assets:precompile`

@schneems Like you said what happens if this is a Sintara app? Surely it makes sense to fail hard for rails then?

**Comment by drubin** [comment]
Just want to say failing silently means you can't rely on automatic builds and tools to detect deploy failures.

**Comment by bbonamin** [comment]
Issue also happens here with a Rails app.
e.g. if my Rakefile uses rspec:
```ruby
require 'rspec/core/rake_task'
```
This fails silently during the deployment as rspec is not installed on the production group.
The workaround has been to only do this "require" if the Rails environment is test or development, but we would expect the deployment to fail if the Rakefile could not be loaded, since rake db:migrate, rake assets:precompile and such don't work at all.

**Comment by bbonamin** [comment]
> What happens is we use rake -P to detect available tasks. When this fails we can't reliably know if that's because you made a syntax error in your Rakefile and you really really relied on us to run rake assets:precompile or if it's because you didn't even ever consider we would try to run rake tasks for you (i.e. people deploying sinatra etc. don't expect us to run rake tasks) and you would be pissed if we suddenly stopped the deploy there.

I think it would be safe to assume that if Rails is detected or the Asset Pipeline is detected, then you should be able to run `rake -P` and not have it fail, otherwise you could end up with a deploy with broken assets.

**Comment by halilim** [comment]
I experience this from time to time as well. Mostly the reason is either a missing environment variable or a dev/test-only something which breaks in production.

I'm wondering what kind of workaround would get the build fail in such situations...

**Comment by gareth** [comment]
:+1: 

Is there a big overhead to making this behaviour [fail-fast on rake error] only happen in the Rails-specific language pack, or is it just a case of low priority because it's not a widespread problem?
