### ISSUE TITLE
Don't write database.yml for ActiveRecord 4.1+

### ISSUE THREAD

**Issue by damonmorgan** [heroku/heroku-buildpack-ruby#364]
Commit https://github.com/heroku/heroku-buildpack-ruby/commit/41dd02b147674e6bb793e9ddb3df47601eae0655 stopped writing `config/database.yml` in Rails 4.1 apps but it would actually be better if it stopped it writing for any apps using ActiveRecord 4.1+ (for example I have a Sinatra app using ActiveRecord 4.2 where I would like to be able to set additional options like pool size in my config/database.yml).

**Comment by schneems** [comment]
Yep, I agree, it's on the radar but hasn't been a priority. Could you stub out a minimal patch for me with an example sinatra app?

**Comment by afeld** [comment]
Closed by #404, yes?

**Comment by shaqq** [comment]
Out of curiosity, why would we need to overwrite the `config/database.yml` for non-Rails apps? It seems like the `config/database.yml` is overwritten because of Railties, no? I can't see how a Sinatra app w/ ActiveRecord would be affected.

So there's this gem: https://github.com/janko-m/sinatra-activerecord/blob/master/lib/sinatra/activerecord.rb

But that doesn't affect us since we deploy [Napa](https://github.com/bellycard/napa) apps and have our own way of setting up ActiveRecord

**Comment by schneems** [comment]
Turns out there were some big caveats. I added a note to the changelog entry https://devcenter.heroku.com/changelog-items/709

**Comment by shaqq** [comment]
@schneems Could you point me to the relevant section in that changelog entry? I can't seem to find it...
