### ISSUE TITLE
Change default server to nginx/passenger

### ISSUE THREAD

**Issue by namxam** [heroku/heroku-buildpack-ruby#371]
I don't know about others, but wouldn't it make sense to support a different default stack for rails apps on heroku? From my experience, using nginx with passenger is a pretty decent solution to run most rails apps. It requires far less configuration and tuning than other servers and supports features such as gzipping assets.

Before I start to build a custom buildpack, I would like to know what's your view on that topic. Wouldn't it make sense to support such a setup by default?

**Comment by schneems** [comment]
We won't inject external dependencies into your app that aren't present in your source control. That's why we warn when rails_12factor isn't present but don't stop you from deploying or inject it.

We currently recommend puma and we emit a warning when you deploy without a Procfile that points to this doc https://devcenter.heroku.com/articles/ruby-default-web-server. 

>  support a different default stack for rails apps on heroku

You can run passenger on heroku right now, here's a demo app from them that does just that https://github.com/phusion/passenger-ruby-heroku-demo.
