### ISSUE TITLE
how to support centos or redhat stack

### ISSUE THREAD

**Issue by chenwenhao03** [heroku/heroku-buildpack-ruby#379]
Hi
I want to to use ruby buildpack in centos6 stack, but failed. It seems recompiling ruby & bunlder is a solution through error logs .
How to compile the binary dependencies such as ruby, bundler etc.
 Could U give me a hand .
Thanks!
Wenhao

**Comment by schneems** [comment]
You'll need to compile bundler, node, and ruby to run on centos. Once you've got that, put them somewhere publicly accessible.

Once you've done that you'll need to set https://github.com/heroku/heroku-buildpack-ruby/blob/e1482d5b00fd692dc10b1965f3a3e0b53e2e0fdc/lib/language_pack/base.rb#L18

In your build server. Then when you deploy your compiled files will be used instead of ours.

**Comment by crohr** [comment]
@chenwenhao03 you might be interested in the precompiled binaries that we're maintaining for ruby, node, bundler, etc. for the Ubuntu/Debian/CentOS/RHEL/SUSE distributions ([example](http://blog.packager.io/post/101342252191/one-liner-to-get-a-precompiled-ruby-on-your-own)).

They can be used with the ruby buildpack by setting the `BUILDPACK_VENDOR_URL` to `https://s3-external-1.amazonaws.com/pkgr-buildpack-ruby/current/centos-6` for instance.

Depending on what you're trying to achieve, you might also be interested in the [pkgr](https://github.com/crohr/pkgr) gem and/or the corresponding hosted service at [Packager.io](https://packager.io).
