### ISSUE TITLE
Need ability to set environment variables in #build_bundler

### ISSUE THREAD

**Issue by packetmonkey** [heroku/heroku-buildpack-ruby#407]
I use multibuildpack to load graphicsmagick into my slug while also having a gem with a native extension that requires graphicsmagick. In order to make this work I had to fork the ruby build pack so I could set some environment variables during slug compilation so the build tools could find the library on disk.

One of the complications of this was the actual directory the slug is compiled in changes every time, so the path had to be determined at slug compilation time.

Here are the steps I had to add to the `#build_bundler` method

``` ruby
gm_path         = File.expand_path "#{pwd}/#{slug_vendor_base}/../../../graphicsmagick"
gm_include_path = "#{gm_path}/include/GraphicsMagick"
gm_lib_path     = "#{gm_path}/lib"
gm_ldflags      = "-L/#{gm_path}/lib"
gm_pkg_config   = "#{gm_path}/lib/pkgconfig"

env_vars       = {
            "BUNDLE_GEMFILE"                => "#{pwd}/Gemfile",
            "BUNDLE_CONFIG"                 => "#{pwd}/.bundle/config",
            "CPATH"                         => noshellescape("#{yaml_include}:#{gm_include_path}:$CPATH"),
            "CPPATH"                        => noshellescape("#{yaml_include}:#{gm_include_path}:$CPPATH"),
            "LIBRARY_PATH"                  => noshellescape("#{yaml_lib}:#{gm_lib_path}:$LIBRARY_PATH"),
            "LDFLAGS"                       => noshellescape("#{gm_ldflags}"),
            "PKG_CONFIG_PATH"               => noshellescape("#{gm_pkg_config}"),
            "RUBYOPT"                       => syck_hack,
            "NOKOGIRI_USE_SYSTEM_LIBRARIES" => "true"
}
```

Now that's my use case. It's not appropriate to add those custom changes to everyone's ruby build pack but what I think is a reasonable change is the ability to set or add to those environment variables and provide a way to make them relative to the slug_vendor_base.

I'm not sure what the best way to implement that would be, or if it's even appropriate for me to do that and PR the change in, but currently the only way I know to build gems with native extension that require on non-standard build packs is to fork the ruby build pack and hard code them in as above.

Any thoughts are appreciated.

Thanks!

**Comment by schneems** [comment]
> I had to fork the ruby build pack so I could set some environment variables during slug compilation

We explicitly disallow the user from setting some environment variables like GEM_PATH otherwise it REALLY screws up the default installation case, however everything else you've got here should work. We use whatever values you set in your `heroku config`. However some of the values you're setting there look like they need to be dynamic. I've tried setting BUNDLE_GEMFILE to a different directory than the default won't work. I've tried it: https://github.com/heroku/heroku-buildpack-ruby/pull/351 and never got it working.

**Comment by packetmonkey** [comment]
The variables do need to be dynamic because they need to point to the path of the files during slug compilation and that changes because a temporary directory is used with a different name for every compile.

Is it possible to expose the slug_vendor_base directory path as an environment variable that we could use in other environment variables? That would allow me to do something like

```console
heroku config:set PKG_CONFIG_PATH="$SLUG_VENDOR_BASE/../../../graphicsmagick/lib/pkgconfig:$PKG_CONFIG_PATH"
```

Assuming that variable gets evaluated after $SLUG_VENDOR_BASE is set.

**Comment by stcorbett** [comment]
I am running into the same kinds of issues with the compilation of native extensions in the linkparser gem. Passing static paths into the bundler options is not doing the trick, dynamically setting paths based on where the `bundle install` is running works. I am looking for a place to set up the environment needed to install linkparser on heroku - ideally without using a custom heroku ruby buildpack. I figure future maintenance will be easier if I'm on the mainline buildpack.

Have you seen any progress on this issue with Heroku?

**Comment by schneems** [comment]
I think relative paths should work? If not then the directory where the app is built is different from where the app is run.

**Comment by stcorbett** [comment]
@schneems - Yeah, the app is built in a directory like `/tmp/build_898932484`. This post has a discription of the build process that matches what I'm seeing: https://gist.github.com/perplexes/5357663

The bug that comes up is around the compilation of a native extension in a ruby gem - the gem wants to find a binary that I've added via a custom buildpack - the binary is in the build directory: /tmp/build_xxx/vendor/binary-name, but it will actually be in /app/vendor/binary-name after slug-compilation is done - which is also where the binary was built with the custom buildpack. Needless to say, I'm currently working around this issue by making a sym-link from the /app/vendor location to the /temp/build_xxx/vendor location during slug-compilation (a highly hack'ish solution).

There are a few better solutions to this. I'm planning on further tweaking the heroku-ruby buildpack so that it handles the setup for the native extension compilation in a clean manner. If there were another hook or two in the existing heroku-ruby buildpack we'd have an even cleaner solution - either one where I could use a special key in an environment variable to pull up the slug compilation location - or some kind of handling for the sym-linking of binary extensions into their permanent locations during slug compilation.

**Comment by MatzFan** [comment]
Did anyone get a workable solution to this, it does seem a major flaw in the Ruby platform on Heroku? Having same trouble with gem `rmagick` not picking up the ImageMagick binary installed by `heroku-buildpack-imagemagick` and instead compiling against the pre-installed one.

**Comment by obromios** [comment]
In @schneems [post](https://github.com/heroku/heroku-buildpack-ruby/issues/407#issuecomment-128755268) he states that it does not appear possible to set `BUNDLE_GEM` to a different directory. From this [next_rails issue](https://github.com/fastruby/next_rails/issues/71) it appears that it is not possible to set `BUNDLE_GEM` to `Gemfile.next` in a reliable fashion, i.e. it can change but during the heroku deploy process it can be ignored.  Is that correct?  Is this an issue with the heroku ruby buildpack?

**Comment by obromios** [comment]
We have done more work on the next_rails issue and it appears that what is happening in our case is that the Heroku ruby buildpack ignores the `BUNDLE_GEMFILE` variable and always bundles only the original Gemfile.lock, but then it tries to run rake using the `BUNDLE_GEMFILE` variable and so it breaks.  This is inconsistent usage, so seem to me that it is a bug in the buildpack rather than a lack of functionality, so should we mark this issue as a bug?
