### ISSUE TITLE
Open for extension?

### ISSUE THREAD

**Issue by jodosha** [heroku/heroku-buildpack-ruby#442]
Hi all and thanks for the openness on Heroku buildpacks.
I've noticed that all the compile steps are modeled after the Rake tasks defined by Rails.

I'm sure that Rails is the most common web framework deployed on your systems. Would you like to consider to make deployment process open of extensions for other Rack based apps?

For instance, after [the last step of compile](https://github.com/heroku/heroku-buildpack-ruby/blob/ad2eb907be59a9ffea203ff08f39f0233f8dc37e/lib/language_pack/ruby.rb#L105), it would be great to invoke a method like `run_deploy_hook`. Defined like this:

``` ruby
def run_deploy_hook
  instrument 'ruby.run_deploy_hook' do
    deploy_hook = Pathname.new('bin/deploy')

    if deploy_hook.exist?
      run("#{deploy_hook}")
    end
  end
end
```

In this way, developers can run their own script at the deploy time.

---

I'm opening this issue because soon [Lotus](http://lotusrb.org) will support assets precompilation at the deploy time. That is done via CLI command like `bundle exec lotus assets precompile`. Another example are database migrations, which still use CLI command instead of Rake.

We really want a great integration with Heroku. This new feature can be helpful for all the Ruby ecosystem, and other Rack frameworks. What's your opinion about this?

Thanks in advance for considering this enhancement.

Luca

**Comment by mrbongiolo** [comment]
+1

**Comment by karimmtarek** [comment]
:+1:

**Comment by hlegius** [comment]
As Luca said, it would be a great improvement and a big encouragement for other Ruby developers to start deploying with Heroku easily as it is for Rails apps.

:+1:

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by jxxcarlson** [comment]
:+1:

**Comment by schneems** [comment]
It's a problem near and dear to my heart. So much so that I wrote up an implementation almost a year ago. Here's the implementation and a longer conversation https://github.com/heroku/heroku-buildpack-ruby/pull/330

The `rake assets:precompile` is a standard hook across all Ruby deploys, not just Rails. https://github.com/heroku/heroku-buildpack-ruby/blob/ad2eb907be59a9ffea203ff08f39f0233f8dc37e/lib/language_pack/ruby.rb#L789-L803

The short term work around would be to hack into the existing hook

```
$ cat Rakefile

task "assets:precompile" do
  `lotus  assets precompile`
end
```

I do this all the time. If you still wanted to run the original task you can do it via

```
task "assets:precompile" do
  # custom code here
  Rake::Task["assets:precompile"].invoke
end
```

This is similar to calling super on a method. Also rake has an `extend` functionality but I can never remember the syntax so I directly invoke instead.

**Comment by jodosha** [comment]
@schneems Thanks for the quick reply.

The long term goal for Lotus was to remove Rake as a dependency. Right now we only have test runners for RSpec and Minitest, but we can easily port to CLI app.

> It's a problem near and dear to my heart. So much so that I wrote up an implementation almost a year ago. Here's the implementation and a longer conversation

Does that means there is no chance to have this deploy hook implemented?

**Comment by schneems** [comment]
Modern ruby versions ship with Rake in the std lib so you would only need a Rakefile.

**Comment by elbouillon** [comment]
:+1:

**Comment by jodosha** [comment]
@schneems Your idea of `finish:deploy` Rake task (#330) would be just great :sparkling_heart: . Any reason why it wasn't merged yet? Thank you :smile:

**Comment by wobrien** [comment]
:+1:

**Comment by baob** [comment]
:+1:

**Comment by jodosha** [comment]
@schneems In the meantime we're adding Lotus support for Heroku via Rake tasks. :smile: https://github.com/lotus/lotus/issues/421

**Comment by joneslee85** [comment]
:+1:, I think this is a great feature that would benefit other frameworks too

**Comment by bryanp** [comment]
We're needing something similar for deploying [Pakyow](https://pakyow.org) apps. For now we forked this buildpack and created an `app:prelaunch` build step: https://github.com/metabahn/heroku-buildpack-ruby/commit/5077a06ff4879871c5a439be4706ee541e125582. Within that task we can do any number of things specific to the app (e.g. for pakyow-web we clone the latest docs from an external repo).

Whatever it's called I think this feature is greatly needed.

**Comment by SampsonCrowley** [comment]
@schneems this is still a major piece of missing functionality that is extremely surprising not to be supported. 

both the official `node` and `python` buildpacks offer a postbuild hook you can choose to opt in to. ruby should  as well. the default answer when so many users are obviously needing the functionality should definitely not be "override assets:precompile" since `assets:precompile` serves a very specific purpose and a lot of people don't need that extra heroku-only code run every time they compile assets locally. there really should be a `heroku:postbuild` task that users can create locally if needed
