### ISSUE TITLE
Rails asset cache not persisting across builds

### ISSUE THREAD

**Issue by ericboehs** [heroku/heroku-buildpack-ruby#451]
As of [sprockets-rails 3.0.0](https://github.com/rails/sprockets-rails/commit/80164cb0b3eae7dc8a6efab7553a7a8ab4e20c10#diff-b295f4f07d2e863f15e53eb2047cfd1f) (released on Dec 17th), the default asset cache is stored in `tmp/cache/sprockets` rather than `tmp/cache/assets`.

From what I can tell, all Rails builds that are using sprockets-rails 3 are not caching assets between deploys.

To fix this the `default_assets_cache` needs to be changed to `"tmp/cache/sprockets"` in [rails4.rb#L66](https://github.com/heroku/heroku-buildpack-ruby/blob/613defce8ec18b6416d527d2183db93cf8702b28/lib/language_pack/rails4.rb#L66).

I'd submit a PR but I'm not sure if there are other places that need to be fixed or how to go about running the test suite. And for the fact that we'll probably want to conditionally check which version of sprockets-rails they're using.

**Comment by schneems** [comment]
Good catch, thanks! How did you find that? I can't believe I (or anyone else) never noticed this before. Sprockets 3 has been out for a pretty long time. I think we should detect sprockets version and return a different cache location based on version.

**Comment by ericboehs** [comment]
We recently ported a project's front end over to rails. When our deploys started taking 6 minutes instead of 30 seconds I had to figure this out.

After lots of debugging (3 hours actually), I found this solution.

Originally I thought it had to do with the buildpack not caching our browserify-rails stuff. But it turns out we just updated to sprockets 3 when browserify-rails came out. I also thought it had to do with us using multiple build packs. Neither of which were the problem.

After forking the ruby buildpack and `puts`ing everything I could think of, I finally figured it out after getting it to reproduce locally. Removing the `tmp` directory before running the precompile broke it. I thought, that must be what's happening on heroku! The tmp directory isn't being persisted.

**Comment by schneems** [comment]
It's not sprockets. It is something else. Probably `sprockets-rails`

Using the same app and only updating the sprockets version:

```
$ rm -rf tmp/cache/
$ RAILS_ENV=production bundle exec rake assets:precompile
$ bundle show sprockets
/Users/richardschneeman/.gem/ruby/2.3.0/gems/sprockets-2.12.4
$ ls tmp/cache/assets/production/sprockets/
# ...

$ rm -rf tmp/cache/
$ RAILS_ENV=production bundle exec rake assets:precompile
$ bundle show sprockets
/Users/richardschneeman/.gem/ruby/2.3.0/gems/sprockets-3.5.2
$ ls tmp/cache/assets/production/sprockets/v3.0/
# ...
```

**Comment by schneems** [comment]
I guess you didn't say it was sprockets, you said it was sprockets-rails. This was released REALLY recently which would explain why this wasn't seen earlier.

**Comment by ericboehs** [comment]
Yeah. I linked to the sha where it was changed.

https://github.com/rails/sprockets-rails/commit/80164cb0b3eae7dc8a6efab7553a7a8ab4e20c10#diff-b295f4f07d2e863f15e53eb2047cfd1f

**Comment by schneems** [comment]
Sorry, i'm running on turbo mode and apparently glossed over 90% of your issue. You did an amazing job reporting the exact problem, sorry for the extra delay in getting up to speed. I have commit to sprockets-rails. I fixed the issue here https://github.com/rails/sprockets-rails/pull/315 we're looking to cut a 3.0.1 release soon.

**Comment by ericboehs** [comment]
Thanks. Glad I could help. And glad I got to work with the schneems. :D

Looking forward to the release.

**Comment by bjeanes** [comment]
Was this actually fixed or is this otherwise a problem for Rails 3 apps? My assets are never cached between builds. It's very frustrating when iterating on something else (in my current case, a buildpack) and everything else is cached but then the asset step takes 5 minutes :(

**Comment by uniite** [comment]
@bjeanes to clarify, this issue was concerning sprockets 3, which is not the same as Rails 3 (sprockets 3 is meant for Rails 4/5).

In general, I believe assets precompile caching is purposely not available on heroku with Rails 3 without something like https://github.com/ndbroadbent/turbo-sprockets-rails3

**Comment by bjeanes** [comment]
@uniite ah that makes sense; thanks

**Comment by bjeanes** [comment]
Ah bummer but that requires running https://github.com/ndbroadbent/heroku-buildpack-turbo-sprockets as the buildpack which is very very behind the supported ruby one...

**Comment by schneems** [comment]
The version of sprockets/sprockets-rails that is locked with Rails 3 has some bugs around caching which is why the buildpack doesn't support caching for Rails 3. You can manually wire your Rails 3 app up to use memcache as a cache, but I highly recommend not doing it, as you're going to hit a critical bug eventually, and lose hours/days of your life to it before you remember to clear the cache. If you need faster asset builds, the turbo-sprockets gem will make asset compilation faster as it de-duplicates the generation of fingerprint and non-fingerprint assets, however if you need a cache I recommend upgrading to Rails 4 and sticking with the maintained buildpack.

On another note Rails 3.2 is now EOL and not getting security updates anymore.

**Comment by bjeanes** [comment]
Thanks. Yeah a Rails 4 upgrade is definitely on the agenda but I've already had 2-3 false starts with it. It's not possible until we refactor a chcunk of old code first it seems. Anyway thanks
