### ISSUE TITLE
Rails assets:precompile doesn't know about env?

### ISSUE THREAD

**Issue by Machiaweliczny** [heroku/heroku-buildpack-ruby#455]
Guys today I've came into this issue:
I've had deployed app with some method in templates that uses ENV variable to generate link paths.
Then I've changed this variable and was wondering why templates doesn't change. 

Seems like this buildpack caches assets using `MD5` without evaluation  of `.erb`. It took me a while to get why it's not updated so I suggest you either check for changes in ENV while rebuilding assets or maybe run them through .erb or maybe add some info? What you thing about it?

Solution was to change `Rails.application.config.assets.version`. And maybe it's proper way to solve it and nothing should be changed.

**Comment by dmathieu** [comment]
This MD5 is generated by rails itself. This isn't something we can fix in the ruby buildpack. It's how the assets:precompile task works.

As a general note, using ENV variables in your assets isn't a very good idea, as you'll need to redeploy your app to change that value in your assets, which entirely defeats the purpose of config vars.
It also means you can never use features like [pipelines](https://devcenter.heroku.com/articles/pipelines), which will not recompile your assets when promoting a slug from staging to production.

Have you considered not using ENV vars in your assets, and setting config vars in your page's DOM so they can be used by your javascript code?

**Comment by schneems** [comment]
> Guys today I've came into this issue:

We employ engineers of different genders.

As a note MD5 isn't used, hashes are default generated via SHA256 https://github.com/rails/sprockets/blob/a7b20d571012318de6271290fae6c96c06d86635/lib/sprockets/digest_utils.rb#L16, though that's not important to this issue.

I agree with Damien, putting env vars in your assets will cause confusing failures. For instance even though apps restart after env vars are changed assets will not be re-compiled, this is expected behavior. it is possible to change the way that a cache key for an asset is evaluated for example changing the `asset_host` in rails will change the SHA which will cause a re-compile. It may be technically possible to do what you want in rails, but it's not the normally recommended thing. 

What are you using ENV vars for you your assets?

**Comment by Machiaweliczny** [comment]
Thanks for your valuable input. I will try to solve it without using ENV variables.

**Comment by schneems** [comment]
I suggested this in another ticket, thought I would mention it here. If your app relies on env vars, you can add them to your version to effectively get what you want but it has 2 downsides. First it forces a recompile on all assets every time the value changes, second it doesn't take effect when you change the env var, only when you deploy. Likely people wouldn't understand this and be frustrated that the changing env var didn't persist

```
config.assets.version += "#{ ENV['MY_ASSET_URL'] }"
```

Just add one of these for each of the env vars that you use and you're good to go. 

I still recommend not using env vars in assets though.
