### ISSUE TITLE
Don't create a postgres database unless it's required

### ISSUE THREAD

**Issue by dmathieu** [heroku/heroku-buildpack-ruby#532]
[Rails apps](https://github.com/heroku/heroku-buildpack-ruby/blob/857d13c6903f2378b2a41d29cdd8ad0237ceaec9/lib/language_pack/rails2.rb#L84) will always request a postgres add-on in bin/release, while [plain ruby ones](https://github.com/heroku/heroku-buildpack-ruby/blob/857d13c6903f2378b2a41d29cdd8ad0237ceaec9/lib/language_pack/ruby.rb#L763) will only do so if we have the pg gem.

This is causing issues, as customers in orgs could not have postgres whitelisted, and they wouldn't then be able to use review apps (or just create new ruby apps and push to them).

I know there was a previous attempt in checking for the pg gem with rails apps, which failed. How about trying again?

**Comment by hone** [comment]
It's worth trying again since this doesn't affect existing running apps 
but new ones but it will affect pipeline/review apps. For JRuby we need 
to get the list of `pg` equivalent gems to detect over. /cc @jkutner

**Comment by jkutner** [comment]
Here are some know Gems (not a complete list, but probably covers 99% of use):

* `activerecord-jdbcpostgresql-adapter`
* `jdbc-postgres`
* `jdbc-postgresql`
* `sequel`
* `jruby-pg`
* `rjack-jdbc-postgres`
* `tgbyte-activerecord-jdbcpostgresql-adapter`

Sequel is particular difficult because it doesn't have a vendor specific component. It works with whatever URL you give it (`jdbc:postgres://...`, `postgres://...`, `mysql://...`, etc). How is this handled for MRI (i think its the same).

**Comment by dmathieu** [comment]
Is sequel handling the database communication in JRuby?
In MRI, it's only an ORM, and requires the `pg` gem in addition to communicate with the database. So it doesn't seem it should be in the list.

**Comment by jkutner** [comment]
Yea, i thought there was a second gem you had to include, but i can't remember. It not `pg` though.

**Comment by jkutner** [comment]
Ah, i think it's `jdbc-postgres` which is already in the list.
