### ISSUE TITLE
"gems.rb" and "gems.locked" doesn't work

### ISSUE THREAD

**Issue by FranklinYu** [heroku/heroku-buildpack-ruby#534]
This is the prefered file name instead of `Gemfile` and `Gemfile.lock`.

**Comment by schneems** [comment]
Thanks for the issue, this bikeshed is going to cause some pain.

**Comment by franklinyu** [comment]
Sorry, I didn't quite get it: what do you mean by "bikeshed"? `Gemfile` is deprecated and won't work in Bundler 2, which is pretty much a consensus within the Bundler team.

**Comment by simonc** [comment]
@franklinyu actually Bundler 2.x will continue to support Gemfile. Support will be removed in 3.0.

I do agree that it would be nice to have support for this though. `gems.rb/gems.locked` will be the _default_ in Bundler 2.0, better to get ahead of the game 😄

@schneems why do you think it's bikeshedding? 🙂

**Comment by tenderlove** [comment]
> why do you think it's bikeshedding?

I think the bike shed that @schneems is referring to is the file name, and I'm firmly in the camp of "leave the color as-is".  I'll explain why.

I think part of the problem is that these files are changing names, which will eventually require all projects that use bundler to change, but the benefit is dubious.  IOW, what is the cost compared to the benefit?  AFAIK the only benefit is to appease people that don't like "file" in a file name, and the down side is the lost time from devs around the world having to update (as well as projects that would otherwise work fine, but don't anymore because the maintainer didn't have time to update, as well as breaking git-bisect).  For an end-user, the cost of change should be proportional to the benefit, and I don't see that here.

**Comment by franklinyu** [comment]
I believe Bundler should still support the old filename scheme for a long time, but as a platform, Heroku should support both. It's project maintainers who choose the filenames, not Heroku. Currently I'm keeping the filename just because Heroku doesn't like it.

**Comment by simonc** [comment]
@tenderlove I totally get your point. Although I can see how normalizing the name can lead to better integration with various tools (text editors, magic-click in terminal, …). It might also do some tree-shaking in the existing gems, pushing aside the one not maintained enough to evolve.

Nevertheless, @franklinyu is right, the discussion around this happened (or is still happening) in Bundlerland and Heroku can decide to boycott this change but I don't think it'd be helpful for anyone 🙂

Cheers,

**Comment by alex-lairan** [comment]
Hi,

I tried to deploy a new app that use `gems.rb` and the buildpack doesn't handle it.

Is heroku boycotting this change ?

**Comment by dentarg** [comment]
There won't be any change, see https://github.com/ruby/setup-ruby/pull/84#issuecomment-686854903 and https://github.com/ruby/setup-ruby/pull/84#issuecomment-687221101

**Comment by ioquatix** [comment]
`setup-ruby` supports both forms and both are part of a public interface. I've created a PR to address at least fix the detection. Not sure if anything else needs to be done.
