### ISSUE TITLE
Rails 5.1 & webpacker require clearing cache before every deploy

### ISSUE THREAD

**Issue by flybayer** [heroku/heroku-buildpack-ruby#562]
A deploy will fail to on `assets:precompile` without any errors in STDOUT or the build log.

```
remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_c3975d9e573c1bf0b4e6b532daa48fde/config/webpack/paths.yml file for setting up webpack paths
remote:        Compiling webpacker assets 🎉
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !	Push rejected to [my app].
```

### Workaround
Run `heroku repo:purge_cache -a [app]` before every deploy

See #561 for more history

/cc @hone

**Comment by Fuffi** [comment]
We're having the same issue

**Comment by schneems** [comment]
Can you open up issues help.heroku.com search for "Rails 5.1 & webpacker require clearing cache before every deploy", so that I can look at your app?

Right now I've got no idea why this is happening. I've seen a few apps with with this reported, but no definitive causes or solutions yet.  I opened https://github.com/rails/webpacker/issues/395 an I'm exploring ways to get more debug output with the command.

**Comment by flybayer** [comment]
@schneems I'm actually using this with dokku instead of Heroku

**Comment by flybayer** [comment]
Update: `node-sass` was my problem even though there was **no** logging indicating this. 

Adding 
```json
"postinstall": "npm rebuild node-sass"
``` 
to my `package.json` scripts as suggested in rails/webpacker#395 has fixed all my deployment problems. 

I no longer need to clear the cache before every deploy.
