### ISSUE TITLE
Warn if the Ruby version isn't explicitly specified in Gemfile

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-ruby#611]
The heroku CLI plugin for clearing the build cache currently special-cases the directories used by the Ruby buildpack for storing Ruby version, and preserves them whilst "clearing" the cache. Ideally the plugin wouldn't do this, and instead the Ruby buildpack would warn users if they do not explicitly specify a Ruby version in their Gemfile, to avoid problems when they use review apps or pipelines.

For more info, see heroku/heroku-repo#70.

**Comment by schneems** [comment]
We do warn if Ruby version isn't explicitly set. We also provide a fallback, and to make that fallback not randomly break when we upgrade ruby versions we must record that fallback version somewhere permanent. For now that place is the poorly named "cache".

The cache is for all purposes a durable store that can be cleared/cleaned. We've re-purposed this folder to be an actual durable store by bypassing the ability to clean or clear it. This is intentional.
