### ISSUE TITLE
Disable Spring EVERYWHERE.

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#818]
I've gotten a few tickets that were resolved by disabling spring with `DISABLE_SPRING=1`. We should consider setting this as a default env var for CI.

**Comment by schneems** [comment]
Internal ticket ID 631486

**Comment by stormsilver** [comment]
One example of what disabling Spring solves is when the app is running a different version of Ruby than what the buildpack installs for its own execution.

For example, as of today the buildpack installs Ruby 2.5.3 to execute itself, but my app uses Ruby 2.6.1. The buildpack correctly installs 2.6.1, but when it arrives at the test phase it complains that I'm running a different version of Ruby than my Gemfile specifies. This happens to be true because Spring has helpfully cached the process for us. Disabling Spring allowed the test phase to fire up the proper version of Ruby.

**Comment by schneems** [comment]
Thanks for the feedback @stormsilver.

Another issue that I saw recently is found in internal ticket id 712875
